# Generated by Django 5.2.6 on 2025-11-08 20:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('rol', models.CharField(choices=[('ADMIN', 'Admin'), ('AUDITOR', 'Auditor'), ('OPERADOR', 'Operador'), ('ROOT', 'Root')], default='OPERADOR', max_length=10, verbose_name='Rol')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('mfa_habilitado', models.BooleanField(default=False, verbose_name='MFA Habilitado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_nif', models.CharField(max_length=20, unique=True, verbose_name='RUT/NIF')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Fantasía')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('direccion_legal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Legal')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('contacto_comercial_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto Comercial')),
                ('contacto_comercial_telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Comercial')),
                ('condiciones_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Condiciones de Pago')),
                ('moneda', models.CharField(default='CLP', max_length=10, verbose_name='Moneda Predeterminada')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('productos_suministrados', models.ManyToManyField(blank=True, related_name='proveedores_asociados', to='catalogo.producto', verbose_name='Productos Suministrados')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Salida'), ('AJ-P', 'Ajuste Positivo'), ('AJ-N', 'Ajuste Negativo'), ('DEV', 'Devolución')], max_length=4, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('bodega', models.CharField(default='BOD-CENTRAL', max_length=100, verbose_name='Bodega')),
                ('lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote')),
                ('serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serie')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('doc_ref', models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc. Referencia')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo (ajustes/devoluciones)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones (notas de operación)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='catalogo.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.proveedor')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
