# Generated by Django 5.2.6 on 2025-11-08 00:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-fecha'], 'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='bodega',
            field=models.CharField(default='BOD-CENTRAL', max_length=100, verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='doc_ref',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento Referencia'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serie'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='condiciones_pago',
            field=models.CharField(blank=True, max_length=100, verbose_name='Condiciones de Pago'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='moneda',
            field=models.CharField(blank=True, default='CLP', max_length=8),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='sitio_web',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Salida'), ('AJ-P', 'Ajuste Positivo'), ('AJ-N', 'Ajuste Negativo'), ('DEV', 'Devolución')], max_length=4, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Fantasía'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(max_length=255, verbose_name='Razón Social'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
