# Generated by Django 5.2.6 on 2025-11-19 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Bodega')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación/Dirección')),
            ],
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.bodega', verbose_name='Bodega'),
        ),
    ]
