# Generated by Django 5.2.6 on 2025-11-07 23:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('ean_upc', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='EAN/UPC')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Breve')),
                ('costo_estandar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Estándar')),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Costo Promedio')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta (Neto)')),
                ('impuesto_iva', models.DecimalField(decimal_places=2, default=19.0, max_digits=4, verbose_name='IVA (%)')),
                ('stock_actual', models.PositiveIntegerField(default=0, editable=False, verbose_name='Stock Actual')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock Máximo')),
                ('punto_reorden', models.PositiveIntegerField(blank=True, null=True, verbose_name='Punto de Reorden')),
                ('perishable', models.BooleanField(default=False, verbose_name='Es Perecible')),
                ('control_por_lote', models.BooleanField(default=False, verbose_name='Control por Lote')),
                ('control_por_serie', models.BooleanField(default=False, verbose_name='Control por Serie')),
                ('es_vegano', models.BooleanField(default=False, verbose_name='Es Vegano')),
                ('sin_gluten', models.BooleanField(default=False, verbose_name='Sin Gluten')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.marca')),
            ],
        ),
    ]
