# Generated by Django 5.2.6 on 2025-10-05 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tiempo_produccion',
        ),
        migrations.AddField(
            model_name='producto',
            name='control_por_lote',
            field=models.BooleanField(default=False, verbose_name='Control por Lote'),
        ),
        migrations.AddField(
            model_name='producto',
            name='impuesto_iva',
            field=models.BooleanField(default=True, verbose_name='Aplica IVA (19%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='perishable',
            field=models.BooleanField(default=False, verbose_name='Es Perecible'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock Máximo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Breve'),
        ),
    ]
