# Generated by Django 5.2.5 on 2025-10-06 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_producto_ingredientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='perishable',
        ),
        migrations.AddField(
            model_name='producto',
            name='es_vegano',
            field=models.BooleanField(default=False, verbose_name='Es Vegano'),
        ),
        migrations.AddField(
            model_name='producto',
            name='perecible',
            field=models.BooleanField(default=False, verbose_name='Es Perecible'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sin_gluten',
            field=models.BooleanField(default=False, verbose_name='Sin Gluten'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta (Neto)'),
        ),
    ]
