# Generated by Django 5.2.5 on 2025-10-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_remove_producto_marca_remove_producto_perishable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='perecible',
        ),
    ]
